package com.dfwl.fleet.security;

public enum PermissionCode {
    VEHICLE_LIST("vehicle:list"),
    VEHICLE_ADD("vehicle:add"),
    VEHICLE_VIEW("vehicle:view"),
    VEHICLE_EDIT("vehicle:edit"),
    VEHICLE_DELETE("vehicle:delete"),
    VEHICLE_BIND_DRIVER("vehicle:bindDriver"),
    VEHICLE_UNBIND_DRIVER("vehicle:unbindDriver"),
    VEHICLE_BINDING_HISTORY("vehicle:bindingHistory"),
    TRAILER_LIST("trailer:list"),
    TRAILER_ADD("trailer:add"),
    TRAILER_EDIT("trailer:edit"),
    TRAILER_BIND_VEHICLE("trailer:bindVehicle"),
    TRAILER_UNBIND_VEHICLE("trailer:unbindVehicle"),
    TRAILER_BINDING_HISTORY("trailer:bindingHistory"),
    DRIVER_LIST("driver:list"),
    DRIVER_ADD("driver:add"),
    DRIVER_EDIT("driver:edit"),
    DRIVER_BIND_VEHICLE("driver:bindVehicle"),
    DRIVER_UNBIND_VEHICLE("driver:unbindVehicle"),
    DRIVER_RESET_PASSWORD("driver:resetPassword"),
    ROUTE_LIST("route:list"),
    ROUTE_CREATE("route:create"),
    ROUTE_EDIT("route:edit"),
    ROUTE_PUBLISH("route:publish"),
    ROUTE_CANCEL("route:cancel"),
    ROUTE_DELETE("route:delete"),
    ROUTE_DEPART("route:depart"),
    ROUTE_UNLOAD("route:unload"),
    ROUTE_VOID("route:void"),
    ROUTE_REACTIVATE("route:reactivate"),
    ROUTE_WEIGHT_ADJUST("route:weight:adjust"),
    EXPENSE_LIST("expense:list"),
    EXPENSE_ADD("expense:add"),
    EXPENSE_EDIT("expense:edit"),
    EXPENSE_DELETE("expense:delete"),
    EXPENSE_ATTRIBUTION_EDIT("expense:attribution:edit"),
    EXPENSE_REVERSAL("expense:reversal"),
    EXPENSE_APPROVAL_VIEW("expense:approval:view"),
    APPROVAL_CREATE("approval:create"),
    APPROVAL_PROCESS("approval:process"),
    APPROVAL_RETURN("approval:return"),
    APPROVAL_HISTORY_VIEW("approval:history:view"),
    APPROVAL_FLOW_MANAGE("approval:flow:manage"),
    TIRE_LIST("tire:list"),
    TIRE_IMPORT("tire:import"),
    TIRE_REQUEST("tire:request"),
    TIRE_APPROVAL_VIEW("tire:approval:view"),
    IMPORT_PREVIEW("import:preview"),
    IMPORT_COMMIT("import:commit"),
    IMPORT_HISTORY("import:history"),
    IMPORT_FAILURE_EXPORT("import:failure:export"),
    SALARY_VIEW("salary:view"),
    SALARY_MANAGE("salary:manage"),
    SALARY_MINE("salary:mine"),
    REPORT_DASHBOARD("report:dashboard"),
    REPORT_PROFIT("report:profit"),
    REPORT_VEHICLE("report:vehicle"),
    REPORT_DRIVER("report:driver"),
    REPORT_ATTENDANCE("report:attendance"),
    REPORT_ENERGY("report:energy"),
    SETTLEMENT_VIEW("settlement:view"),
    SETTLEMENT_GENERATE("settlement:generate"),
    SETTLEMENT_DIFF_VIEW("settlement:diff:view"),
    USER_MANAGE("user:manage"),
    ROLE_MANAGE("role:manage"),
    PERMISSION_MANAGE("permission:manage"),
    AUDIT_VIEW("audit:view");

    private final String code;

    PermissionCode(String code) {
        this.code = code;
    }

    public String code() {
        return code;
    }
}
